src/GLWpfControl/GLWpfControl.xaml.cs
src/GLWpfControlExample/MainWindow.xaml.cs

When the GLWpfControl is being resized, it stops rendering and starts again after 1ms, to avoid lags and save performance

Added resize delay for the rendering method

---

src/GLWpfControl/GLWpfControl.cs
src/GLWpfControl/GLWpfControlSettings.cs

This PR aims to solve a mismatch between "viewport pixels" and "device pixels" while creating framebuffers for OpenGL and Direct3D.
At the moment, UIElement.RenderSize properties Width and Height are used for sizing framebuffers. Actually, they do not take into account that there are displays configured for higher pixel densities compared to the standard 96 dpi (think "retina" displays, or zoom > 100% configured in Display settings on Windows).
In this PR, OpenGL and Direct3D framebuffers will be sized to the actual device pixel size and not the viewport size, allowing for a sharper result on "retina" displays.
As an addition, I'm thinking of exposing the (actual) render width and height of the control as public properties, enabling the user to make correct calls to OpenGL that regard …

WIP Handling of device pixels and viewport pixels

---

src/GLWpfControl/GLWpfControl.cs

- this fixes the blank black/white frames after OnLoaded

[3.x] Move OpenGL context initialization from OnLoaded to Start()

---

src/GLWpfControl/DxGLFramebuffer.cs
src/GLWpfControl/GLWpfControlRenderer.cs

Fixes bug introduced in #24 
DXFramebufferWidth has now:
- Width and Height for device-independent pixels (1/96th of an inch) for rendering transformations in WPF
- FramebufferWidth and FramebufferHeight for the actual size of the framebuffer (they could be equal to Width and Height in case UseDeviceDpi is set to false)

DPI scaling fix: content not covering all the available surface

---

src/GLWpfControl/GLWpfControlRenderer.cs

Quite subtle bug resolved!
If one drags the window from the left or right side, a OnRenderSizeChanged event is triggered, but the framebuffer is not updated because of a small mistake in evaluating the condition for triggering the resize.
This leads to a wide white region appearing on the side of the control.

Bugfix: resizing only width or height doesn't update the framebuffer

---

src/GLWpfControl/GLWpfControl.cs

The CompositionTarget.Render event could fire multiple times for the same frame.
Considering the example project, this issue is easily reproducible by dragging the window, or clicking on the button to re-render the inset control.
This PR makes the render only for the first time for a given frame.
Testing is very welcome! By my side it looks ok.
For reference: 
https://docs.microsoft.com/en-us/dotnet/desktop/wpf/advanced/walkthrough-hosting-direct3d9-content-in-wpf?view=netframeworkdesktop-4.8#to-import-direct3d9-content

Avoiding of rendering multiple times in the same WPF render frame

---

src/GLWpfControl/GLWpfControl.cs

Fixes bug in #26 : when RenderContinuously is updated from False to True, the control doesn't start drawing continuously.
Thanks Daniel for discovering this bug!

Bugfix: update of RenderContinuously not working correctly

---

src/GLWpfControl/GLWpfControl.cs
src/GLWpfControl/UnstartedControlHelper.cs

This PR:
- removes the idiot check, since it prevents the user to attach a Render callback on the XAML (the example is not broken anymore)
- shows a fallback view of the control if Start() is not called, reminding the user to call the Start() method (only when debugging)
This could be ground to other useful checks (eg: check if a Render callback is actually set).

Safety checks improvement for checking Start() call

---

src/GLWpfControl/DxGLFramebuffer.cs

This small modification of the frame buffer allows the stencil tests to be used. That is, in certain cases, extremely fast and useful feature. It allows for example to render an area of nonconvex polygons (even with holes inside) knowing just their boundary. And much more.
This simple change has been originally suggested by Varon. I have made that change and tested on my code - works well.

Adding stencil to the Frame Buffer:  DxGLFrameBuffer.cs

---

src/GLWpfControl/DXGLContext.cs
src/GLWpfControl/GLWpfControlSettings.cs

Sometimes it is needed to call or pass callback to `wglGetProcAddress` for some third-party OpenGL libraries.
This allows to create `GLFWBindingsContext` manually and pass it to `GLWpfControl` and then also use it as `wglGetProcAdress` for such third-party OpenGL libraries.

Add ability to pass custom IBindingsContext to GLWpfControlSettings

---

src/Example/ExampleScene.cs
src/Example/TabbedMainWindowTest.xaml
src/Example/TabbedMainWindowTest.xaml.cs
src/GLWpfControl/DxGLFramebuffer.cs
src/GLWpfControl/GLWpfControl.cs
src/GLWpfControl/GLWpfControlRenderer.cs
src/GLWpfControl/GLWpfControlSettings.cs

Issue [59](https://github.com/opentk/GLWpfControl/issues/59)
Changing the frame buffer format to `A8R8G8B8`, the alpha channel of the color passed to the function GL.ClearColor will determine now the level of transparency of the control.

Configure the control to allow transparency

---

src/GLWpfControl/GLWpfControlRenderer.cs

The `WGL_DX_NV_interop` extension should handle the synchronization between GL and DX.
Closes #51

Remove unecessary call to GL.FLush

---

src/GLWpfControl/GLWpfControl.cs

Simply just added two new properties to help users determine whether they'd like to hook onto events directly with the EventManager or instead handle input themselves. This makes the control more versatile and also acts a workaround to the issue where controls events are being invoked twice; once for the event manager and once for the control.

Fix Events Issue

---

src/GLWpfControl/GLWpfControl.cs
src/GLWpfControl/GLWpfControl.csproj

1) It is redundant
2) If setting RenderContinuously to false in the render handler, an undesired additional last call to the render handler (due to invalidation in OnCompTarget) ; this change fixes this.

removing _needsRedraw

---

src/Example/MainWindow.xaml
src/Example/MainWindow.xaml.cs
src/GLWpfControl/DXGLContext.cs
src/GLWpfControl/GLWpfControl.cs

- Added a `Start` function overload that does not take any arguments; it relies on the `Settings` attached property.
- This required the addition of a new field to check whether the control has been started.
- Modified the example project to showcase both use cases.
Fixes #105
This PR introduces no new dependencies.
I tested this locally on my machine and ensured that everything was still functioning as normal within the example project.
**Test Configuration**:
* Operating System: Windows 10 Home
* Hardware: Intel i7-10710U @ 1.1GHz, 32GB RAM
* Toolchain: VS Community 2022
```xaml
<glWpfControl:GLWpfControl
x:Name="OpenTkControl"
Render="OpenTkControl_OnRender">
<glWpfControl:GLWpfControl.Settings>
<glWpfControl:GLWpfControlSettings MinorVersion="2" MajorVersion="1"/> …
```

Added support to modify the GLWpfControlSettings within XAML front-end.

---

src/GLWpfControl/GLWpfControlRenderer.cs

This adds the same fix to enable software fallback to the 3.x version that was introduced to master recently.

fix remote desktop issue in 3.x

---

src/GLWpfControl/DXGLContext.cs
src/GLWpfControl/GLWpfControlRenderer.cs
src/GLWpfControl/Interop/DXInterop.cs

Since `4.2.3` the control has been broken on some integrated graphics cards.
One of the key differences between the newer versions and `4.2.3` is the use of WDDM share handles.
This PR adds back the share handle use which seems to fix the issue on my AMD Radeon integrated graphics card.
But using any MSAA setting > 0 will result in a crash while my dedicated graphics card can handle MSAA fine.
I've not found any way to query if a specific MSAA version will work or not, maybe we just have to try and if the function fail we have to try again without MSAA...
Fixes #128 
Should fix #130

Try to fix integrated graphics

---

src/GLWpfControl/GLWpfControlRenderer.cs

Now the (older) property FrameBufferHandle is an alias for the (newer) property GLFramebufferHandle.

Fix FrameBufferHandle not being set

---

src/GLWpfControl/DXGLContext.cs

This fixes a couple of things related to `DXGLContext` dispose:
- A call to `DXCloseDeviceNV` with an empty `GLDeviceHandle` crashes with AccessViolationException. This checks if `GLDeviceHandle` isn't empty beforehand.
- Removed finalizer dispose as it might run from any thread and `GlwfWindow` can only be disposed on main thread.
- Added a call to dispose before throwing an exception in ctor to ensure proper clean-up.
In my case I can now properly handle when the control can't initialize on integrated gpus without crashing. Maybe fixes [113](https://github.com/opentk/GLWpfControl/issues/113) and [132](https://github.com/opentk/GLWpfControl/issues/132) as they're similar to what I've encountered (though these may not be related as I now see that NativeWindow also has a finalizer).

Fix DXGLContext dispose

---

src/GLWpfControl/GLWpfControl.cs
src/GLWpfControl/GLWpfControlRenderer.cs

This PR adds a quick and dirty check for trying to create an MSAA framebuffer and if that fails we don't try to create MSAA framebuffers even if the user requests MSAA. This fixes MSAA crashes on many computers.
Partially fixes #140, #138, and #134
It probably doesn't fix the integrated graphics issue.

Fix MSAA crash in many cases.
